USE [master]
GO

/****** Object:  Database [JDBCProject]    Script Date: 2020/10/20 ¤U¤È 07:12:14 ******/
CREATE DATABASE [JDBCProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JDBCProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JDBCProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JDBCProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JDBCProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JDBCProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JDBCProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JDBCProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JDBCProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JDBCProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JDBCProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [JDBCProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JDBCProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JDBCProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JDBCProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JDBCProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JDBCProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JDBCProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JDBCProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JDBCProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JDBCProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JDBCProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JDBCProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JDBCProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JDBCProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JDBCProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JDBCProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JDBCProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JDBCProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [JDBCProject] SET  MULTI_USER 
GO

ALTER DATABASE [JDBCProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JDBCProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JDBCProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JDBCProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JDBCProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JDBCProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [JDBCProject] SET  READ_WRITE 
GO


