USE [JDBCProject]
GO

/****** Object:  Table [dbo].[Wifi_Info]    Script Date: 2020/10/22 ¤W¤È 10:50:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Wifi_Info](
	[SITE_ID] [char](10) NOT NULL,
	[NAME] [nvarchar](65) NOT NULL,
	[AGENCY] [nvarchar](30) NOT NULL,
	[AREACODE] [smallint] NOT NULL,
	[AREANAME] [nvarchar](6) NOT NULL,
	[ADDR] [nvarchar](40) NOT NULL,
	[LONGITUDE] [decimal](11, 8) NOT NULL,
	[LATITUDE] [decimal](12, 10) NOT NULL,
	[VERSION] [int] NULL,
 CONSTRAINT [PK_Wifi_Info] PRIMARY KEY CLUSTERED 
(
	[SITE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Wifi_Info] ADD  CONSTRAINT [DF_Wifi_Info_VERSION]  DEFAULT ((0)) FOR [VERSION]
GO


